'use client';
import { useEffect, useState } from 'react';
import { ArrowLeft, BookOpen, Coffee, MapPin, MessageCircle, Theater, Users, X } from 'lucide-react';

const API_BASE = process.env.NEXT_PUBLIC_API_BASE_URL || 'http://127.0.0.1:80';
type Scene = { id: string; name: string };
type Candidate = { avatar_id: string; display_name?: string; display_summary?: Record<string, unknown> };
type ChatEvent = { event: string; event_id?: string; round?: number; speaker?: string; status?: string; payload?: Record<string, any> };
type Group = { chat_no: string; initiator: { display_name: string }; invited: { display_name: string }; started_at: string; message_count: number; unread: boolean };
const sceneIcons: Record<string, any> = { cafe: Coffee, library: BookOpen, bar: MessageCircle, theater: Theater, lecture: Users };

/** 请求 JSON 接口，统一携带 Cookie 并将后端错误转换成可读异常。 */
async function requestJson(path: string, init?: RequestInit) { const response = await fetch(`${API_BASE}${path}`, { credentials: 'include', ...init }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.detail || data.error?.message || `请求失败(${response.status})`); return data; }

/** 地图与场景选择页，真实场景不可用时显示空状态。 */
export default function TownDemo() {
  const [scenes, setScenes] = useState<Scene[]>([]); const [scene, setScene] = useState<Scene | null>(null); const [groups, setGroups] = useState<Group[]>([]); const [showHistory, setShowHistory] = useState(false); const [error, setError] = useState('');
  useEffect(() => { requestJson('/v1/twin/scenes').then((v) => setScenes(v.items || [])).catch((e) => setError(e.message)); }, []);
  const loadHistory = async () => { try { const value = await requestJson('/v1/twin/chat-groups?page=1&page_size=50'); setGroups(value.items || []); setShowHistory(true); } catch (e) { setError(e instanceof Error ? e.message : '读取聊天记录失败'); } };
  if (scene) return <SceneRoom scene={scene} onBack={() => setScene(null)} onError={setError} />;
  return <div><div className="mb-7 flex items-end justify-between gap-4"><div><p className="mb-2 text-sm font-medium text-[#0084ff]">小镇漫游</p><h1 className="text-3xl font-semibold">选择今天想去的场景</h1><p className="mt-2 text-[#646a73]">你的看山始终是发起方，点击场景后选择匹配方式。</p></div><button onClick={loadHistory} className="rounded-lg border bg-white px-4 py-2 text-sm">Agent 聊天记录 {groups.some((x) => x.unread) && <span className="ml-2 inline-block h-2 w-2 rounded-full bg-red-500" />}</button></div>{error && <p className="mb-4 rounded-lg bg-red-50 p-3 text-sm text-red-600">{error}</p>}<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{scenes.map((item) => { const Icon = sceneIcons[item.id] || MapPin; return <button key={item.id} onClick={() => setScene(item)} className="rounded-2xl border bg-white p-6 text-left shadow-sm transition hover:border-[#0084ff]"><Icon className="text-[#0084ff]" /><h2 className="mt-5 text-lg font-semibold">{item.name}</h2><p className="mt-2 text-sm text-[#646a73]">查看当前场景空闲的看山</p></button>; })}</div>{!scenes.length && !error && <p className="rounded-xl border bg-white p-8 text-center text-sm text-[#646a73]">正在读取场景…</p>}{showHistory && <History groups={groups} close={() => setShowHistory(false)} />}</div>;
}

/** 场景房间，负责三种匹配方式、实时双 Agent 对话和取消。 */
function SceneRoom({ scene, onBack, onError }: { scene: Scene; onBack: () => void; onError: (v: string) => void }) {
  const [candidates, setCandidates] = useState<Candidate[]>([]); const [mode, setMode] = useState<'manual' | 'random' | 'llm'>('manual'); const [target, setTarget] = useState<string | null>(null); const [run, setRun] = useState<string | null>(null); const [events, setEvents] = useState<ChatEvent[]>([]); const [status, setStatus] = useState('idle'); const [round, setRound] = useState(0); const [advanced, setAdvanced] = useState(false);
  useEffect(() => { requestJson(`/v1/twin/scenes/${scene.id}/avatars`).then((v) => setCandidates(v.items || [])).catch((e) => onError(e.message)); }, [scene.id, onError]);
  useEffect(() => { if (!run) return; let source: EventSource | null = null; let timer: ReturnType<typeof setTimeout> | undefined; const connect = () => { const previous = events.length ? events[events.length - 1].event_id : ''; source = new EventSource(`${API_BASE}/v1/twin/dialogues/${run}/events${previous ? `?last_event_id=${encodeURIComponent(previous)}` : ''}`, { withCredentials: true }); const handle = (message: MessageEvent) => { const value: ChatEvent = JSON.parse(message.data); setEvents((old) => old.some((x) => x.event_id === value.event_id) ? old : [...old, value]); setRound(value.round || 0); if (value.status) setStatus(value.status); }; source.onmessage = handle; ['status', 'topic_selected', 'round_progress', 'evaluation', 'error'].forEach((name) => source?.addEventListener(name, handle)); source.onerror = () => { source?.close(); timer = setTimeout(connect, 1000); }; }; connect(); return () => { source?.close(); if (timer) clearTimeout(timer); }; }, [run]);
  useEffect(() => { if (!run || !['completed', 'evaluation_failed', 'cancelled', 'failed'].includes(status) || advanced) return; setAdvanced(true); requestJson(`/v1/twin/dialogues/${run}/advance-day`, { method: 'POST' }).catch(() => undefined); }, [run, status, advanced]);
  const start = async () => { try { const data = await requestJson('/v1/twin/dialogues', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ scene_id: scene.id, match_mode: mode, target_avatar_id: mode === 'manual' ? target : null, max_rounds: 10 }) }); setRun(data.run_id); setStatus('queued'); setEvents([]); } catch (e) { onError(e instanceof Error ? e.message : '启动对话失败'); } };
  const cancel = async () => { if (run) await requestJson(`/v1/twin/dialogues/${run}/cancel`, { method: 'POST' }).catch(() => undefined); }; const finished = ['completed', 'evaluation_failed', 'cancelled', 'failed'].includes(status);
  return <div><button onClick={onBack} className="mb-5 flex items-center gap-2 text-sm text-[#646a73]"><ArrowLeft size={16} />返回地图</button><p className="text-sm text-[#0084ff]"><MapPin size={15} className="mr-1 inline" />{scene.name}</p><h1 className="mt-2 text-3xl font-semibold">让我的看山认识一位新朋友</h1><div className="my-5 flex flex-wrap gap-2">{(['manual', 'random', 'llm'] as const).map((item) => <button key={item} onClick={() => setMode(item)} className={`rounded-md px-3 py-2 text-sm ${mode === item ? 'bg-[#0084ff] text-white' : 'bg-white ring-1 ring-[#ddd]'}`}>{item === 'manual' ? '指定模式' : item === 'random' ? '随机模式' : '匹配模式'}</button>)}</div>{mode === 'manual' && <div className="mb-5 grid gap-3 sm:grid-cols-3">{candidates.map((item) => <button key={item.avatar_id} onClick={() => setTarget(item.avatar_id)} className={`rounded-xl border bg-white p-4 text-left ${target === item.avatar_id ? 'border-[#0084ff] ring-2 ring-[#cfe6fb]' : ''}`}><p className="font-medium">{item.display_name || '看山'}</p><p className="mt-1 text-xs text-[#646a73]">空闲，可开始交流</p></button>)}</div>}{!run && <button disabled={mode === 'manual' && !target} onClick={start} className="rounded-lg bg-[#0084ff] px-5 py-3 text-sm text-white disabled:opacity-50">开始交流</button>}{run && <section className="mt-6 rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><p className="font-semibold">实时对话 · 第 {round}/10 轮</p><p className="mt-1 text-xs text-[#8590a6]">状态：{status === 'running' ? '正在思考' : status}</p></div>{!finished && <button onClick={cancel} className="rounded-md border px-3 py-2 text-sm">提前结束</button>}</div><div className="mt-5 space-y-3">{events.filter((x) => x.event === 'message').map((item) => <div key={item.event_id} className={`rounded-xl p-3 text-sm ${item.speaker === 'A' ? 'bg-[#e6f3ff]' : 'bg-[#f6f7f8]'}`}><span className="mr-2 text-xs text-[#8590a6]">看山 {item.speaker}</span>{item.payload?.content}</div>)}</div>{finished && <p className="mt-5 rounded-lg bg-[#f0f7ff] p-3 text-sm text-[#235b91]">本轮交流已结束，正在保存聊天记录和计算匹配度。</p>}</section>}</div>;
}

/** 聊天组历史列表，详情由后端按 chat_no 权限校验后返回。 */
function History({ groups, close }: { groups: Group[]; close: () => void }) { const [detail, setDetail] = useState<any>(null); const open = async (chatNo: string) => { const value = await requestJson(`/v1/twin/chat-groups/${chatNo}/messages`); setDetail(value); }; return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/30 p-5"><div className="max-h-[85vh] w-full max-w-2xl overflow-auto rounded-2xl bg-white p-6"><div className="flex items-center justify-between"><h2 className="text-xl font-semibold">Agent 聊天记录</h2><button onClick={close}><X /></button></div>{detail ? <div><button onClick={() => setDetail(null)} className="my-4 text-sm text-[#0084ff]">返回列表</button><div className="space-y-3">{detail.messages.map((m: any) => <div key={m.message_id} className="rounded-lg bg-[#f6f7f8] p-3 text-sm"><p className="text-xs text-[#8590a6]">{m.sender_name}</p>{m.content}</div>)}</div></div> : <div className="mt-5 space-y-3">{groups.map((g) => <button key={g.chat_no} onClick={() => open(g.chat_no)} className="w-full rounded-lg border p-4 text-left"><p className="font-medium">{g.initiator.display_name} ↔ {g.invited.display_name}</p><p className="mt-1 text-xs text-[#8590a6]">{new Date(g.started_at).toLocaleString()} · {g.message_count} 条消息 {g.unread && <span className="ml-2 text-red-500">●</span>}</p></button>)}{!groups.length && <p className="py-8 text-center text-sm text-[#646a73]">暂无已处理的聊天记录</p>}</div>}</div></div>; }
